"""Conexão com o PostgreSQL do escritório e criação do schema.

O banco fica num servidor PostgreSQL (versão 15, a última com instalador
testado no Windows Server 2016) e cada PC conecta nele por endereço e porta.
Onde está esse servidor, e com que usuário entrar, é configuração de cada PC
— guardada na pasta local (ver pasta_local), nunca no banco."""
from __future__ import annotations

import datetime as dt
import json
import os
import sys
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from pathlib import Path

import psycopg
from psycopg import errors
from psycopg.adapt import Dumper
from psycopg.pq import TransactionStatus
from psycopg.types.numeric import IntDumper

# Rodando do código-fonte, a pasta local fica ao lado do projeto (bom pra
# desenvolvimento — dá pra achar fácil). Empacotado com o PyInstaller,
# __file__ aponta pra dentro da pasta do próprio .exe, em Arquivos de
# Programas, onde usuário comum não grava.
#
# Empacotado, ela vai pra %PROGRAMDATA% (C:\ProgramData), que é a pasta de
# dados da MÁQUINA, não a de cada conta do Windows: a conexão configurada
# uma vez vale pra quem quer que entre naquele PC. O instalador é que abre a
# permissão de escrita dessa pasta pros usuários comuns (ver [Dirs] em
# controle_lucros.iss).
NOME_DA_PASTA = "ControleDeLucros"


def _pasta_dados_padrao() -> Path:
    if getattr(sys, "frozen", False):
        base = os.getenv("PROGRAMDATA") or os.getenv("LOCALAPPDATA") or str(Path.home())
        return Path(base) / NOME_DA_PASTA / "data"
    return Path(__file__).resolve().parent.parent / "data"


def pasta_local() -> Path:
    """A pasta de dados desta máquina. Guarda a configuração da conexão, as
    preferências, os backups e o registro de falhas — coisas de um PC só.

    CONTROLE_LUCROS_DADOS (usado pelos testes) troca a pasta, pra rodar a
    suíte não gravar na configuração de quem usa o sistema."""
    override = os.environ.get("CONTROLE_LUCROS_DADOS")
    return Path(override) if override else _pasta_dados_padrao()


# Quanto tempo uma gravação espera a vez quando outro PC está mexendo nas
# mesmas linhas. Sem limite, um PC travado no meio de uma gravação deixaria
# os outros parados olhando pra tela; com ele, vira aviso de "tente de novo".
ESPERA_DE_BLOQUEIO_MS = 10_000

# Quanto esperar o servidor responder ao conectar. O padrão do libpq é
# esperar pra sempre — com o servidor desligado, o programa parecia
# congelado antes da tela de login.
ESPERA_DE_CONEXAO_S = 5

SCHEMA = """
CREATE TABLE IF NOT EXISTS empresa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_chamada TEXT NOT NULL,
    nome TEXT NOT NULL,
    cnpj TEXT,
    capital_social DOUBLE PRECISION NOT NULL DEFAULT 0,
    quantidade_cotas DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS socio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cpf TEXT,
    tipo_pessoa TEXT NOT NULL DEFAULT 'fisica' CHECK (tipo_pessoa IN ('fisica', 'juridica'))
);

CREATE TABLE IF NOT EXISTS alteracao_contratual (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    numero INTEGER NOT NULL,
    data TEXT NOT NULL,
    nome_empresa TEXT NOT NULL,
    capital_social DOUBLE PRECISION NOT NULL,
    quantidade_cotas DOUBLE PRECISION NOT NULL,
    descricao TEXT,
    fechada INTEGER NOT NULL DEFAULT 0,
    UNIQUE(empresa_id, numero)
);

CREATE TABLE IF NOT EXISTS vinculo_societario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    socio_id INTEGER NOT NULL REFERENCES socio(id),
    percentual_capital DOUBLE PRECISION NOT NULL,
    quantidade_cotas DOUBLE PRECISION,
    data_entrada TEXT NOT NULL,
    data_saida TEXT,
    alteracao_entrada_id INTEGER REFERENCES alteracao_contratual(id),
    alteracao_saida_id INTEGER REFERENCES alteracao_contratual(id),
    observacao TEXT
);

CREATE TABLE IF NOT EXISTS distribuicao_lucro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    ano_base INTEGER NOT NULL,
    socio_id INTEGER NOT NULL REFERENCES socio(id),
    valor_distribuido DOUBLE PRECISION NOT NULL DEFAULT 0,
    pro_labore DOUBLE PRECISION NOT NULL DEFAULT 0,
    irrf DOUBLE PRECISION NOT NULL DEFAULT 0,
    UNIQUE(empresa_id, ano_base, socio_id)
);

-- Lançamento trimestral da distribuição. Existe separado de distribuicao_lucro
-- (e não como quatro colunas dela) porque nem toda empresa distribui por
-- trimestre: quem não usa continua com um lançamento anual só, sem quatro
-- campos vazios no meio do caminho. Ao salvar um trimestre, a soma dos
-- trimestres do ano é gravada de volta na distribuição anual.
CREATE TABLE IF NOT EXISTS distribuicao_trimestral (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    ano_base INTEGER NOT NULL,
    trimestre INTEGER NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    socio_id INTEGER NOT NULL REFERENCES socio(id),
    valor_distribuido DOUBLE PRECISION NOT NULL DEFAULT 0,
    pro_labore DOUBLE PRECISION NOT NULL DEFAULT 0,
    irrf DOUBLE PRECISION NOT NULL DEFAULT 0,
    UNIQUE(empresa_id, ano_base, trimestre, socio_id)
);

CREATE INDEX IF NOT EXISTS idx_distribuicao_trimestral_periodo
    ON distribuicao_trimestral (empresa_id, ano_base);

CREATE TABLE IF NOT EXISTS periodo_distribuicao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    ano_base INTEGER NOT NULL,
    fechado INTEGER NOT NULL DEFAULT 0,
    fechado_em TEXT,
    UNIQUE(empresa_id, ano_base)
);

CREATE TABLE IF NOT EXISTS movimentacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    socio_id INTEGER NOT NULL REFERENCES socio(id),
    tipo TEXT NOT NULL CHECK (tipo IN (
        'emprestimo_empresa_para_socio',
        'emprestimo_socio_para_empresa',
        'adiantamento_lucro',
        'devolucao_capital'
    )),
    valor DOUBLE PRECISION NOT NULL,
    data TEXT NOT NULL
);

-- Diferente do resto do banco (que guarda dinheiro como DOUBLE PRECISION), os
-- valores do informe são INTEIRO de centavos: é documento fiscal entregue à
-- Receita, e um centavo de erro de arredondamento já é documento errado.
-- BIGINT porque INTEGER estoura em R$ 21 milhões.
CREATE TABLE IF NOT EXISTS informe_rendimento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id),
    socio_id INTEGER NOT NULL REFERENCES socio(id),
    ano_base INTEGER NOT NULL,
    codigo_beneficiario TEXT NOT NULL DEFAULT '',
    natureza_rendimento TEXT NOT NULL DEFAULT 'RENDIMENTO DO TRABALHO ASSALARIADO NO PAÍS',
    q3_total_rendimentos BIGINT NOT NULL DEFAULT 0,
    q3_previdencia_oficial BIGINT NOT NULL DEFAULT 0,
    q3_previdencia_complementar BIGINT NOT NULL DEFAULT 0,
    q3_pensao_alimenticia BIGINT NOT NULL DEFAULT 0,
    q3_irrf BIGINT NOT NULL DEFAULT 0,
    q4_parcela_isenta_65 BIGINT NOT NULL DEFAULT 0,
    q4_parcela_isenta_13_65 BIGINT NOT NULL DEFAULT 0,
    q4_diarias_ajudas_custo BIGINT NOT NULL DEFAULT 0,
    q4_pensao_molestia_grave BIGINT NOT NULL DEFAULT 0,
    q4_lucros_dividendos BIGINT NOT NULL DEFAULT 0,
    q4_valores_socio_microempresa BIGINT NOT NULL DEFAULT 0,
    q4_indenizacoes_rescisao BIGINT NOT NULL DEFAULT 0,
    q4_juros_mora BIGINT NOT NULL DEFAULT 0,
    q4_outros BIGINT NOT NULL DEFAULT 0,
    q5_decimo_terceiro BIGINT NOT NULL DEFAULT 0,
    q5_irrf_decimo_terceiro BIGINT NOT NULL DEFAULT 0,
    q5_outros BIGINT NOT NULL DEFAULT 0,
    emprestimo_saldo BIGINT NOT NULL DEFAULT 0,
    saida_sociedade_data TEXT NOT NULL DEFAULT '',
    cotas_inicio DOUBLE PRECISION NOT NULL DEFAULT 0,
    cotas_fim DOUBLE PRECISION NOT NULL DEFAULT 0,
    cota_valor_nominal BIGINT NOT NULL DEFAULT 0,
    informacoes_complementares TEXT NOT NULL DEFAULT '',
    responsavel_nome TEXT NOT NULL DEFAULT '',
    atualizado_em TEXT NOT NULL,
    UNIQUE(empresa_id, ano_base, socio_id)
);

CREATE INDEX IF NOT EXISTS idx_informe_socio_ano ON informe_rendimento (socio_id, ano_base);

CREATE TABLE IF NOT EXISTS usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    login TEXT NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL,
    senha_salt TEXT NOT NULL,
    admin INTEGER NOT NULL DEFAULT 0,
    ativo INTEGER NOT NULL DEFAULT 1,
    criado_em TEXT NOT NULL
);

-- Como ler uma planilha de origem: cada campo do cadastro e a letra da coluna
-- em que ele está naquele arquivo. Guardado como JSON porque é um conjunto de
-- pares campo->letra que muda com os campos do sistema; uma coluna por campo
-- viraria ALTER TABLE a cada campo novo, e nada aqui é consultado por campo.
CREATE TABLE IF NOT EXISTS layout_importacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    linha_inicial INTEGER NOT NULL DEFAULT 2,
    colunas_json TEXT NOT NULL,
    criado_em TEXT NOT NULL,
    atualizado_em TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS log_atividade (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuario(id) ON DELETE SET NULL,
    usuario_nome TEXT NOT NULL,
    data_hora TEXT NOT NULL,
    acao TEXT NOT NULL,
    entidade TEXT NOT NULL,
    entidade_id INTEGER,
    detalhes TEXT
);
"""

# Na ordem em que podem ser preenchidas sem ferir chave estrangeira — é a
# ordem que o backup grava e a restauração lê.
TABELAS = (
    "empresa",
    "socio",
    "alteracao_contratual",
    "vinculo_societario",
    "distribuicao_lucro",
    "distribuicao_trimestral",
    "periodo_distribuicao",
    "movimentacao",
    "informe_rendimento",
    "usuario",
    "layout_importacao",
    "log_atividade",
)


# ------------------------------------------------ configuração local --
#
# O que é DESTE computador e não pode morar no banco: principalmente COMO
# chegar no banco. Cada PC precisa saber sozinho o endereço do servidor
# antes de conseguir abrir qualquer coisa.
ARQUIVO_CONFIG_LOCAL = "configuracao_local.json"
CHAVE_CONEXAO = "conexao"


def ler_config_local() -> dict:
    try:
        # utf-8-sig: arquivo editado no Bloco de Notas pode vir com BOM.
        return json.loads((pasta_local() / ARQUIVO_CONFIG_LOCAL).read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return {}


def gravar_config_local(chave: str, valor) -> None:
    """None apaga a chave. Relê o arquivo antes de gravar pra não perder o
    que outra parte do programa guardou nele."""
    dados = ler_config_local()
    if valor is None:
        dados.pop(chave, None)
    else:
        dados[chave] = valor
    arquivo = pasta_local() / ARQUIVO_CONFIG_LOCAL
    arquivo.parent.mkdir(parents=True, exist_ok=True)
    arquivo.write_text(json.dumps(dados, ensure_ascii=False, indent=2), encoding="utf-8")


@dataclass
class ParametrosConexao:
    """Onde está o PostgreSQL e com que usuário entrar nele.

    A senha fica em texto na configuração local: qualquer conta do Windows
    daquele PC consegue lê-la. O usuário do banco deve ser um só do sistema
    (não o postgres), dono apenas do banco do Controle de Lucros."""

    servidor: str
    porta: int = 5432
    banco: str = "controle_lucros"
    usuario: str = "controle_lucros"
    senha: str = ""

    def descricao(self) -> str:
        return f"{self.banco} em {self.servidor}:{self.porta} (usuário {self.usuario})"

    def argumentos(self) -> dict:
        return {
            "host": self.servidor,
            "port": int(self.porta),
            "dbname": self.banco,
            "user": self.usuario,
            "password": self.senha,
            "connect_timeout": ESPERA_DE_CONEXAO_S,
            "application_name": "Controle de Lucros",
            # Sem keepalive, um PC cuja rede caiu continua "conectado" pro
            # servidor por horas, segurando o que estivesse travando.
            "keepalives": 1,
            "keepalives_idle": 30,
            "keepalives_interval": 10,
            "keepalives_count": 3,
        }

    @classmethod
    def de_dicionario(cls, dados: dict) -> ParametrosConexao:
        return cls(
            servidor=str(dados.get("servidor") or ""),
            porta=int(dados.get("porta") or 5432),
            banco=str(dados.get("banco") or "controle_lucros"),
            usuario=str(dados.get("usuario") or "controle_lucros"),
            senha=str(dados.get("senha") or ""),
        )


def conexao_configurada() -> ParametrosConexao | None:
    """A conexão escolhida pra este PC, ou None se ninguém configurou ainda.

    CONTROLE_LUCROS_PG (usado pelos testes) passa na frente, no formato de
    string de conexão do libpq ("host=... port=... dbname=... user=...")."""
    override = os.environ.get("CONTROLE_LUCROS_PG")
    if override:
        partes = psycopg.conninfo.conninfo_to_dict(override)
        return ParametrosConexao(
            servidor=str(partes.get("host", "localhost")),
            porta=int(partes.get("port", 5432)),
            banco=str(partes.get("dbname", "controle_lucros")),
            usuario=str(partes.get("user", "controle_lucros")),
            senha=str(partes.get("password", "")),
        )
    dados = ler_config_local().get(CHAVE_CONEXAO)
    if not dados or not dados.get("servidor"):
        return None
    return ParametrosConexao.de_dicionario(dados)


def definir_conexao(parametros: ParametrosConexao) -> None:
    """Aponta este PC pro servidor. Só vale na próxima conexão — a já aberta
    continua onde estava."""
    gravar_config_local(CHAVE_CONEXAO, asdict(parametros))


def precisa_configurar() -> bool:
    """Instalação nova, que ainda não sabe onde fica o servidor."""
    return conexao_configurada() is None


class ConexaoNaoConfigurada(psycopg.OperationalError):
    """Nenhum servidor escolhido pra este PC."""


# ------------------------------------------------------------ conexão --


class _DataComoTexto(Dumper):
    """date e datetime vão pro banco como texto ISO, igual o sqlite3 fazia.

    As datas moram em colunas TEXT ('2024-03-31'); sem isto, uma data
    passada como date virava tipo date no servidor, e comparar texto com date
    é erro no PostgreSQL."""

    oid = 0  # tipo desconhecido: o servidor deduz pela coluna comparada

    def dump(self, obj):
        texto = obj.isoformat(sep=" ") if isinstance(obj, dt.datetime) else obj.isoformat()
        return texto.encode()


class Linha(tuple):
    """Linha de resultado que se lê por posição (linha[0]) ou por nome de
    coluna (linha["nome"]), e vira dicionário com dict(linha) — o mesmo
    contrato do sqlite3.Row, do qual o código inteiro depende."""

    _indice: dict[str, int]

    def __getitem__(self, chave):
        if isinstance(chave, str):
            return tuple.__getitem__(self, self._indice[chave])
        return tuple.__getitem__(self, chave)

    def keys(self) -> list[str]:
        return list(self._indice)


def _fabrica_de_linhas(cursor):
    if cursor.description is None:
        return tuple
    indice: dict[str, int] = {}
    for posicao, coluna in enumerate(cursor.description):
        indice.setdefault(coluna.name, posicao)

    def fazer(valores):
        linha = Linha(valores)
        linha._indice = indice
        return linha

    return fazer


# Comandos que abrem transação. Leitura roda fora dela, como no sqlite3: uma
# tela parada exibindo dados não pode deixar transação aberta no servidor,
# que seguraria travas e impediria, por exemplo, restaurar um backup.
_COMANDOS_DE_ESCRITA = ("INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "TRUNCATE")


class Conexao:
    """A conexão com o servidor, com o mesmo jeito de usar do sqlite3:
    conn.execute(...) devolve o cursor, gravações ficam pendentes até
    conn.commit(), e leituras não prendem nada.

    Duas diferenças do PostgreSQL que ficam escondidas aqui:
    - erro dentro de uma transação a invalida inteira; a conexão desfaz a
      transação na hora, em vez de deixar todos os comandos seguintes
      falharem com "current transaction is aborted";
    - conexão que caiu (servidor reiniciado, rede fora) é refeita no próximo
      comando, em vez de o programa precisar ser fechado."""

    def __init__(self, parametros: ParametrosConexao):
        self.parametros = parametros
        self._conn = self._abrir()
        self._cache: dict | None = None

    def _abrir(self) -> psycopg.Connection:
        conn = psycopg.connect(
            **self.parametros.argumentos(), autocommit=True, row_factory=_fabrica_de_linhas
        )
        conn.adapters.register_dumper(bool, IntDumper)  # flags moram em colunas INTEGER
        conn.adapters.register_dumper(dt.date, _DataComoTexto)
        conn.adapters.register_dumper(dt.datetime, _DataComoTexto)
        conn.execute(f"SET lock_timeout = {ESPERA_DE_BLOQUEIO_MS}")
        return conn

    @property
    def em_transacao(self) -> bool:
        return self._conn.info.transaction_status != TransactionStatus.IDLE

    @contextmanager
    def leituras_repetidas_em_cache(self):
        """Dentro do bloco, a mesma consulta com os mesmos parâmetros vai ao
        servidor uma vez só. Pra relatórios que só leem e repetem muito a
        mesma pergunta (a visão geral pede a lista de sócios uma vez por
        empresa por ano). Gravar dentro do bloco esvazia o cache, pra
        ninguém ler o que já mudou."""
        self._cache = {}
        try:
            yield
        finally:
            self._cache = None

    def execute(self, sql: str, parametros=None):
        if self._cache is not None:
            comando = sql.lstrip().split(None, 1)[0].upper() if sql.strip() else ""
            if comando != "SELECT":
                self._cache.clear()
            else:
                try:
                    chave = (sql, tuple(parametros or ()))
                    hash(chave)
                except TypeError:
                    chave = None
                if chave is not None:
                    if chave not in self._cache:
                        cur = self._executar(sql, parametros)
                        self._cache[chave] = (cur.description, cur.fetchall())
                    return _ResultadoGuardado(*self._cache[chave])
        return self._executar(sql, parametros)

    def _executar(self, sql: str, parametros=None) -> psycopg.Cursor:
        if self._conn.broken:
            self._conn = self._abrir()
        comando = sql.lstrip().split(None, 1)[0].upper() if sql.strip() else ""
        try:
            if comando in _COMANDOS_DE_ESCRITA and not self.em_transacao:
                self._conn.execute("BEGIN")
            return self._conn.execute(sql, parametros)
        except psycopg.Error:
            if not self._conn.broken and self.em_transacao:
                self._conn.execute("ROLLBACK")
            raise

    def executemany(self, sql: str, lista_de_parametros) -> None:
        """Muitas gravações de uma vez, sem uma ida e volta ao servidor por
        linha — é o que faz a restauração de um backup grande terminar em
        segundos pela rede. Só serve pra gravação: abre transação."""
        if self._conn.broken:
            self._conn = self._abrir()
        try:
            if not self.em_transacao:
                self._conn.execute("BEGIN")
            with self._conn.cursor() as cur:
                cur.executemany(sql, lista_de_parametros)
        except psycopg.Error:
            if not self._conn.broken and self.em_transacao:
                self._conn.execute("ROLLBACK")
            raise

    def commit(self) -> None:
        if not self._conn.broken and self.em_transacao:
            self._conn.execute("COMMIT")

    def rollback(self) -> None:
        if not self._conn.broken and self.em_transacao:
            self._conn.execute("ROLLBACK")

    def close(self) -> None:
        self._conn.close()

    @property
    def closed(self) -> bool:
        return self._conn.closed


class _ResultadoGuardado:
    """O que o cursor devolveria, lido de novo do cache — só o que o código
    usa de um cursor: fetchone, fetchall, iteração e description."""

    def __init__(self, description, linhas):
        self.description = description
        self._linhas = iter(linhas)

    def fetchone(self):
        return next(self._linhas, None)

    def fetchall(self):
        return list(self._linhas)

    def __iter__(self):
        return self._linhas


def connect(parametros: ParametrosConexao | None = None) -> Conexao:
    parametros = parametros or conexao_configurada()
    if parametros is None:
        raise ConexaoNaoConfigurada("Este computador ainda não sabe em que servidor está o banco.")
    return Conexao(parametros)


def testar_conexao(parametros: ParametrosConexao) -> str:
    """Conecta, confere que dá pra criar as tabelas e desconecta. Devolve a
    versão do servidor; o erro, se houver, sobe pra quem chamou explicar."""
    conn = connect(parametros)
    try:
        versao = conn.execute("SHOW server_version").fetchone()[0]
        _conferir_permissao_de_criar(conn)
        return str(versao)
    finally:
        conn.close()


def _conferir_permissao_de_criar(conn: Conexao) -> None:
    """Desde o PostgreSQL 15 só o dono do banco cria tabelas no schema
    public. Sem essa checagem, um banco criado com o dono errado só daria
    erro na primeira abertura, com a mensagem crua do servidor."""
    pode = conn.execute(
        "SELECT has_schema_privilege(current_user, 'public', 'CREATE')"
    ).fetchone()[0]
    if not pode:
        raise errors.InsufficientPrivilege(
            f"O usuário {conn.parametros.usuario} não pode criar tabelas no banco "
            f"{conn.parametros.banco}."
        )


# ---------------------------------------------------- explicar erros --


def explicar_erro(erro: BaseException) -> str:
    """O texto do erro do banco trocado por algo que a pessoa entenda e saiba
    o que fazer. Com o banco no servidor, quem lê "connection refused" não
    tem como adivinhar que é o serviço do PostgreSQL que está parado."""
    if not isinstance(erro, psycopg.Error):
        return str(erro)
    if isinstance(erro, ConexaoNaoConfigurada):
        return str(erro)
    # Erro ao conectar não chega com código (sqlstate): só o texto do
    # servidor diz o que foi. E o PostgreSQL instalado num Windows em
    # português responde em português — por isso as duas línguas.
    texto = str(erro).lower() if isinstance(erro, psycopg.OperationalError) else ""
    if isinstance(erro, errors.InvalidPassword) or _contem(
        texto, "password authentication failed", "senha falhou", "role \"", "papel \""
    ):
        return (
            "O servidor recusou o usuário ou a senha do banco. Confira os dados da conexão "
            "com quem instalou o PostgreSQL."
        )
    if isinstance(erro, errors.InvalidCatalogName) or (
        _contem(texto, "database \"", "banco de dados \"") and _contem(texto, "does not exist", "não existe")
    ):
        return (
            "O servidor está no ar, mas o banco com esse nome não existe nele. Confira o nome "
            "do banco nos dados da conexão — ou peça pra criá-lo (veja o manual, "
            "\"Servidor PostgreSQL\")."
        )
    if isinstance(erro, errors.InvalidAuthorizationSpecification) or "pg_hba.conf" in texto:
        return (
            "O servidor não aceita conexões deste computador. No servidor, o arquivo "
            "pg_hba.conf precisa liberar a rede do escritório (veja o manual, \"Servidor "
            "PostgreSQL\")."
        )
    if isinstance(erro, errors.InsufficientPrivilege):
        return (
            f"{erro}\n\nO banco precisa pertencer ao usuário que o sistema usa (CREATE DATABASE "
            "... OWNER ...). Veja o manual, \"Servidor PostgreSQL\"."
        )
    if isinstance(erro, (errors.LockNotAvailable, errors.DeadlockDetected)):
        return (
            "Outro computador está gravando nesses mesmos dados agora. Espere alguns segundos "
            "e tente de novo."
        )
    if isinstance(erro, psycopg.OperationalError):
        parametros = conexao_configurada()
        onde = f"{parametros.servidor}:{parametros.porta}" if parametros else "o servidor"
        if "timeout" in texto or "timed out" in texto:
            return (
                f"O servidor do banco ({onde}) não respondeu. Confira se este computador está "
                "na rede, se o servidor está ligado e se o firewall dele libera a porta."
            )
        if "refused" in texto or "recusad" in texto:
            return (
                f"O servidor ({onde}) está na rede, mas o PostgreSQL não atendeu. Confira se o "
                "serviço do PostgreSQL está rodando nele e se a porta está certa."
            )
        if "translate host name" in texto or "resolve" in texto or "unknown host" in texto:
            return (
                f"Não encontrei o servidor \"{parametros.servidor if parametros else ''}\" na "
                "rede. Confira o nome ou use o endereço IP dele."
            )
        return (
            f"A conexão com o servidor do banco ({onde}) falhou ou caiu. O que você estava "
            "gravando pode não ter sido salvo — confira a rede e tente de novo."
        )
    return str(erro)


def _contem(texto: str, *trechos: str) -> bool:
    return any(trecho in texto for trecho in trechos)


# ------------------------------------------------------------ schema --

# Chave da trava que serializa a criação do schema: dois PCs abrindo o
# programa pela primeira vez ao mesmo tempo tentariam criar as mesmas
# tabelas, e o CREATE TABLE IF NOT EXISTS não é à prova de corrida.
_TRAVA_DO_SCHEMA = 7_216_043_901


def init_schema(conn: Conexao) -> None:
    conn.execute("BEGIN")
    try:
        conn.execute("SELECT pg_advisory_xact_lock(%s)", (_TRAVA_DO_SCHEMA,))
        conn.execute(SCHEMA)
        conn.commit()
    except BaseException:
        conn.rollback()
        raise
